version: '3.7'

services:
  gobarber-api:
    build: .
    image: gobarber
    container_name: gobarber-api
    command: yarn start:${NODE_ENV}
    volumes:
      - .:/home/node/api
      - ./node_modules:/home/node/api/node_modules
      - ./src/config/database.docker.js:/home/node/api/src/config/database.js
    ports:
      - '3333:3333'
    depends_on:
      - gobarber-postgres
      - gobarber-mongodb
      - gobarber-redis
    networks:
      - gobarber-network

  gobarber-postgres:
    image: postgres
    container_name: gobarber-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - gobarber-postgres-data:/data
    networks:
      - gobarber-network

  gobarber-mongodb:
    image: mongo
    container_name: gobarber-mongodb
    ports:
      - '27017:27017'
    volumes:
      - gobarber-mongodb-data:/data
    networks:
      - gobarber-network

  gobarber-redis:
    image: redis:alpine
    container_name: gobarber-redis
    ports:
      - '6379:6379'
    volumes:
      - gobarber-redis-data:/data
    networks:
      - gobarber-network

volumes:
  gobarber-postgres-data:
    name: gobarber-postgres-data
  gobarber-mongodb-data:
    name: gobarber-mongodb-data
  gobarber-redis-data:
      name: gobarber-redis-data

networks:
  gobarber-network:
    name: gobarber-network
    driver: bridge

